### ISSUE TITLE
Build Qt on OS X locally and upload

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/qt-feedstock#15] opened 2016-12-13 14:11 UTC
We need to build the recipe here on `OS X` to be consistent conda-forge pinnings.

@ccordoba12 if you are going to try this make sure to inspect the package to avoid linking to any local lib and to use `conda-forge` as the preffered channel while building.

**Comment by ccordoba12** [comment] 2016-12-13 16:20
How do I make the necessary inspection? I mean, what commands do I have to run?

**Comment by ocefpaf** [comment] 2016-12-13 16:22
`conda inspect linkages -p $PREFIX qt`

and 

`conda inspect objects -p $PREFIX qt`

If you are using `conda-build 2` you can also do

`conda inspect prefix-lengths path/to/package.tar.bz2`

**Comment by gillins** [comment] 2017-01-11 01:14
@ccordoba12, @jakirkham have you had a chance to build with 10.9? Any trouble with the recipe?

**Comment by ccordoba12** [comment] 2017-01-11 02:57
Unfortunately I don't have the XCode version used in conda-forge and I don't have free time to install it and work on this right now, sorry.

I'll have some free time in a month or so.

**Comment by jakirkham** [comment] 2017-01-11 03:50
At our recent meeting, I agreed to do it. Just need the time to do so. Thanks for the nudge, @gillins .

**Comment by jakirkham** [comment] 2017-01-12 06:00
So just starting on this now. I noticed that it appears to pick up the system `zlib`. Did you see this as well, @gillins ? In any event, have run into this pain point with other Mac builds before. Will try to look into what we did to fix them.

<details>

```
Build .................. libs tools translations
Configuration ..........  silent release largefile stl precompile_header mmx 3dnow sse sse2 sse3 ssse3 sse4_1 sse4_2 avx  x86_64 absolute_library_soname  minimal-config small-config medium-config large-config full-config no-pkg-config phonon phonon-backend accessibility opengl shared reduce_exports ipv6 getaddrinfo ipv6ifname getifaddrs system-jpeg system-png png system-tiff no-freetype system-zlib nis cups iconv openssl corewlan concurrent xmlpatterns multimedia audio-backend svg script scripttools declarative release  x86_64
Debug .................. no
Qt 3 compatibility ..... no
QtDBus module .......... no
QtConcurrent code ...... yes
QtGui module ........... yes
QtScript module ........ yes
QtScriptTools module ... yes
QtXmlPatterns module ... yes
Phonon module .......... yes
Multimedia module ...... auto
SVG module ............. yes
WebKit module .......... yes
JavaScriptCore JIT ..... To be decided by JavaScriptCore
Declarative module ..... yes
Declarative debugging ...yes
Support for S60 ........ no
Symbian DEF files ...... no
STL support ............ yes
PCH support ............ yes
MMX/3DNOW/SSE/SSE2/SSE3. yes/yes/yes/yes/yes
SSSE3/SSE4.1/SSE4.2..... yes/yes/yes
AVX..................... yes
Graphics System ........ default
IPv6 support ........... yes
IPv6 ifname support .... yes
getaddrinfo support .... yes
getifaddrs support ..... yes
Accessibility .......... yes
NIS support ............ yes
CUPS support ........... yes
Iconv support .......... yes
Glib support ........... auto
GStreamer support ...... auto
PulseAudio support ..... auto
Large File support ..... yes
GIF support ............ plugin
TIFF support ........... plugin (system)
JPEG support ........... plugin (system)
PNG support ............ yes (system)
MNG support ............ plugin (qt)
zlib support ........... system
Session management ..... auto
OpenGL support ......... yes (Desktop OpenGL)
OpenVG support ......... no
SQLite support ......... plugin (qt)
OpenSSL support ........ yes (run-time)
Alsa support ........... no
CoreWlan support ....... yes
ICD support ............ auto
libICU support ......... auto
Use system proxies ..... no

```

</details>

**Comment by jakirkham** [comment] 2017-01-12 08:33
So the build completed successfully, but the test failed. Log snippet from the tests below.

<details>

```
TEST START: qt-4.8.7-6
Deleting work directory, /Users/vagrant/miniconda/conda-bld/recipe_1484200503607/work/qt-everywhere-opensource-src-4.8.7
updating index in: /Users/vagrant/miniconda/conda-bld/osx-64
updating index in: /Users/vagrant/miniconda/conda-bld/noarch

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    qt-4.8.7                   |                6        35.7 MB  local

The following NEW packages will be INSTALLED:

    ca-certificates: 2016.9.26-0 conda-forge
    freetype:        2.6.3-1     conda-forge
    icu:             56.1-4      conda-forge
    jpeg:            9b-0        conda-forge
    libiconv:        1.14-4      conda-forge
    libpng:          1.6.26-0    conda-forge
    libtiff:         4.0.6-7     conda-forge
    libxml2:         2.9.3-9     conda-forge
    openssl:         1.0.2h-3    conda-forge
    qt:              4.8.7-6     local      
    xz:              5.2.2-0     conda-forge
    zlib:            1.2.8-3     conda-forge

+ source /Users/vagrant/miniconda/bin/activate /Users/vagrant/miniconda/conda-bld/recipe_1484200503607/_t_env
+ /bin/bash -x -e /Users/vagrant/miniconda/conda-bld/recipe_1484200503607/test_tmp/run_test.sh
+ cd test
+ qmake hello.pro
WARNING: /Users/vagrant/miniconda/conda-bld/recipe_1484200503607/_t_env/mkspecs/default/qmake.conf:12: Unable to find file for inclusion ../../common/mac.conf
WARNING: /Users/vagrant/miniconda/conda-bld/recipe_1484200503607/_t_env/mkspecs/default/qmake.conf:13: Unable to find file for inclusion ../../common/gcc-base-macx.conf
WARNING: /Users/vagrant/miniconda/conda-bld/recipe_1484200503607/_t_env/mkspecs/default/qmake.conf:14: Unable to find file for inclusion ../../common/clang.conf
+ make
c -stdlib=libc++ -mmacosx-version-min=10.9 -DQT_NO_DEBUG -DQT_CORE_LIB -I../../_t_env/mkspecs/default -I. -I/QtCore -I. -o main.o main.cpp
make: c: No such file or directory
make: [main.o] Error 1 (ignored)
stdlib=libc++ -mmacosx-version-min=10.9 -o hello main.o     -lQtCore 
/bin/sh: -mmacosx-version-min=10.9: command not found
make: [hello] Error 127 (ignored)
+ ./hello
/Users/vagrant/miniconda/conda-bld/recipe_1484200503607/test_tmp/run_test.sh: line 6: ./hello: No such file or directory
TESTS FAILED: qt-4.8.7-6
```

</details>

**Comment by jakirkham** [comment] 2017-01-12 15:21
I think maybe it has something to do with the fact that I installed the command line tools instead of a full XCode install. Will try installing XCode and see how that goes.

**Comment by gillins** [comment] 2017-01-12 21:50
I have the full XCode install and am seeing the same thing. Not sure what is going on - will look into it some more. I don't think I properly tested this all through with conda-build 2.x (got impatient with my old Mac - sorry)...

I think the "system" libs are OK - I think this refers to libraries that already exist rather than Qt's own builds. The recipe does specifically tell it to use the "system" libraries for `zlib` etc. I could be wrong though...

**Comment by jakirkham** [comment] 2017-01-12 21:58
Hmm...interesting. Was thinking it might be related to this [issue]( https://github.com/Homebrew/legacy-homebrew/issues/32348 ) even though this is an older version of Qt. Have XCode 6.1.1 installed now (6.1 crashed when I tried to open it). May give it a try tonight anyways to see if it helps.

> I think the "system" libs are OK - I think this refers to libraries that already exist rather than Qt's own...

Yeah, sorry, I think I mistook this for something else. After some reading it became clear that this means external libs like you have said. I'm not worried especially after seeing the results of `conda` running `install_name_tool`.

**Comment by gillins** [comment] 2017-01-12 22:04
I checked some of my older tests and `conda-build` 1.x is fine, however as you found with 2.x `qmake` seems to forget what configuration it is to use. I've already had to put one big hack in for longer path lengths so it actually builds with 2.x, possibly have to do this somewhere else as well.

**Comment by jakirkham** [comment] 2017-01-12 22:28
Have you tried setting `--croot` and/or `--no-build-id`?

**Comment by gillins** [comment] 2017-01-13 00:48
What is happening is that the `qmake.conf` for the `unsupported/macx-clang-libc++` platform is copied to `mkspecs/default/qmake.conf` (and then read by `qmake`) but the include paths within that file are now wrong since it was down an extra level (in 'unsupported'). I'm not sure why this was working before, but the path length doesn't seem to be a factor. 

The workaround I came up with is below and seems to work fine for me, a bit of googling seem to suggest this is the way to force the right platform to be selected. Would it be better to have `QMAKESPEC` set in an `activate.sh` so other software can access it? Or patch `mkspecs/default/qmake.conf` (seems fiddly)?  Any thoughts appreciated...

I'm still trying to work out why conda-build 1.x works - seems truly mysterious since the same problem looks like it should happen there also, but I suspect setting `QMAKESPEC` wouldn't hurt anyway.

```
diff --git a/recipe/run_test.sh b/recipe/run_test.sh
index b224c56..fef4c42 100644
--- a/recipe/run_test.sh
+++ b/recipe/run_test.sh
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+if [ $(uname) == Darwin ]; then
+  export QMAKESPEC=unsupported/macx-clang-libc++
+fi
```

**Comment by jakirkham** [comment] 2017-01-13 01:38
Would `qmake -set` work in this case?

**Comment by gillins** [comment] 2017-01-13 04:49
Didn't seem to work for me:
```
$ qmake -set QMAKESPEC unsupported/macx-clang-libc++
$ qmake -o Makefile hello.pro
WARNING: /Users/sam/miniconda3/conda-bld/recipe_1484212415866/_t_env/mkspecs/default/qmake.conf:12: Unable to find file for inclusion ../../common/mac.conf
WARNING: /Users/sam/miniconda3/conda-bld/recipe_1484212415866/_t_env/mkspecs/default/qmake.conf:13: Unable to find file for inclusion ../../common/gcc-base-macx.conf
WARNING: /Users/sam/miniconda3/conda-bld/recipe_1484212415866/_t_env/mkspecs/default/qmake.conf:14: Unable to find file for inclusion ../../common/clang.conf
```

**Comment by pkgw** [comment] 2017-01-14 00:24
if it's any help, [here's](https://github.com/pkgw/conda-recipes/blob/master/recipes/qt4/build.sh) the build script I use to build Qt4 with conda-build 2.x on my personal OSX machine. It uses `g++` — is that going to be incompatible with the `clang` approach?

Also, that script outlines something that I'd like to do: copy this package to one called `qt4` that's parallel-installable with the main, version 5, `qt` package, since I have some software that's stuck on using Qt4 but I'd like the rest of my software to track the most recent versions. But that's for a bit farther in the future.

**Comment by gillins** [comment] 2017-01-14 02:44
Thanks @pkgw. Yes conda-forge uses `clang++` and `libc++` which is incompatible with `g++`/`libstdc++`. Previously there has been a mix of compilers and libraries which caused crashes. We are trying to standardize on `clang++` on `osx` for conda-forge. @jakirkham might be able to comment on the history of this, but I understand `clang++`/`libc++` is compatible with most `osx` versions where `g++` support has been removed and users would need extra libs to have `g++`-built packages working on later OS versions.

The fact that `clang++`/`libc++` is tagged 'unsupported' by Qt4 (even though it seems to work fine) seems to be causing us some headaches here.

I *think* there is a `qt5` package in the works that will be compatible with this `qt` package. Yes this package probably should have been called `qt4`, and this is my fault... Sorry. Perhaps we should rename it soon.

**Comment by ccordoba12** [comment] 2017-01-14 05:22
> Yes this package probably should have been called qt4, and this is my fault... Sorry. Perhaps we should rename it soon.

@gillins, we (i.e. Continuum) tried to make Qt4 and Qt5 two different packages but were not able to do it. The problem is `qt.conf`, which tells Qt how it's been installed (i.e. it defines the installation layout) and (unfortunately) has the same name and location for both versions.

After trying for more than six months to do it, we found this approach too brittle and prone to failures. That's why I'd suggest to not follow that path.

**Comment by gillins** [comment] 2017-01-14 09:24
> After trying for more than six months

Ah i didn't hear that. That is a shame...

**Comment by gillins** [comment] 2017-01-16 02:34
See https://github.com/conda-forge/qt-feedstock/pull/23. This is my best attempt at working around this problem. Let me know if you have any comments.

I also tried to modify `qmake` to fallback on this spec if $QMAKESPEC wasn't set but that somehow broke the Qt build itself so this seemed the least risky.

**Comment by jakirkham** [comment] 2017-02-06 02:08
What commit should I be building for Qt4 at this point? Just `HEAD` of `qt4` or some particular commit?

**Comment by gillins** [comment] 2017-02-06 02:25
Just `HEAD` (of the `qt4` branch).

**Comment by jakirkham** [comment] 2017-02-06 05:47
Am getting a crash. The files it mentions to attach don't have much interesting going on. However, they do make mention of the 10.7.0 run time.

<details>

```
$ conda build recipe/
BUILD START: qt-4.8.7-7
    (actual version deferred until further download or env creation)
updating index in: /Users/vagrant/miniconda/conda-bld/osx-64
updating index in: /Users/vagrant/miniconda/conda-bld/noarch

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2016.9.26  |                0         162 KB  conda-forge

The following NEW packages will be INSTALLED:

    ca-certificates: 2016.9.26-0 conda-forge
    freetype:        2.7-1       conda-forge
    icu:             58.1-0      conda-forge
    jpeg:            9b-0        conda-forge
    libpng:          1.6.28-0    conda-forge
    libtiff:         4.0.6-7     conda-forge
    openssl:         1.0.2h-3    conda-forge
    xz:              5.2.2-0     conda-forge
    zlib:            1.2.11-0    conda-forge


WARNING: conda-build appears to be out of date. You have version 2.1.2 but the
latest version is 2.1.3. Run

conda update -n root conda-build

to get the latest version.

Source cache directory is: /Users/vagrant/miniconda/conda-bld/src_cache
Downloading source to cache: qt-everywhere-opensource-src-4.8.7.tar.gz
Downloading http://download.qt-project.org/official_releases/qt/4.8/4.8.7/qt-everywhere-opensource-src-4.8.7.tar.gz
Success
Extracting download
Applying patch: '/Users/vagrant/qt-feedstock/recipe/acceptance.patch'
patching file configure
Hunk #2 succeeded at 4616 (offset 19 lines).
Hunk #3 succeeded at 4647 (offset 19 lines).
Hunk #4 succeeded at 4734 (offset 20 lines).
Applying patch: '/Users/vagrant/qt-feedstock/recipe/config.cpp.longpath.patch'
patching file configure
Applying patch: '/Users/vagrant/qt-feedstock/recipe/qmake-arch.patch'
patching file configure
Hunk #1 succeeded at 5093 (offset 4 lines).
Applying patch: '/Users/vagrant/qt-feedstock/recipe/osx_deployment_target_10.9_qmake.conf.patch'
patching file mkspecs/unsupported/macx-clang-libc++/qmake.conf
Applying patch: '/Users/vagrant/qt-feedstock/recipe/osx_rpath.qmake.conf.patch'
patching file mkspecs/common/mac.conf
Applying patch: '/Users/vagrant/qt-feedstock/recipe/qpaintengine_mac.patch'
patching file src/gui/painting/qpaintengine_mac.cpp
BUILD START (revised): qt-4.8.7-7
Package: qt-4.8.7-7
source tree in: /Users/vagrant/miniconda/conda-bld/recipe_1486359815152/work/qt-everywhere-opensource-src-4.8.7
+ source /Users/vagrant/miniconda/bin/activate /Users/vagrant/miniconda/conda-bld/recipe_1486359815152/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
+ chmod +x configure
++ uname
+ '[' Darwin == Linux ']'
++ uname
+ '[' Darwin == Darwin ']'
+ for x in OSX_ARCH CFLAGS CXXFLAGS LDFLAGS
+ unset OSX_ARCH
+ for x in OSX_ARCH CFLAGS CXXFLAGS LDFLAGS
+ unset CFLAGS
+ for x in OSX_ARCH CFLAGS CXXFLAGS LDFLAGS
+ unset CXXFLAGS
+ for x in OSX_ARCH CFLAGS CXXFLAGS LDFLAGS
+ unset LDFLAGS
+ mkdir src/3rdparty/webkit/Source/lib
+ chmod +x configure
++ uname -m
+ ./configure -prefix /Users/vagrant/miniconda/conda-bld/recipe_1486359815152/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl -libdir /Users/vagrant/miniconda/conda-bld/recipe_1486359815152/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -bindir /Users/vagrant/miniconda/conda-bld/recipe_1486359815152/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin -headerdir /Users/vagrant/miniconda/conda-bld/recipe_1486359815152/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/qt -datadir /Users/vagrant/miniconda/conda-bld/recipe_1486359815152/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl -L /Users/vagrant/miniconda/conda-bld/recipe_1486359815152/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -I /Users/vagrant/miniconda/conda-bld/recipe_1486359815152/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -release -fast -no-qt3support -nomake examples -nomake demos -nomake docs -opensource -openssl -system-zlib -system-libpng -system-libtiff -system-libjpeg -no-framework -arch x86_64 -platform unsupported/macx-clang-libc++ -silent
Stack dump:
0.	Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple x86_64-apple-macosx10.7.0 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name xcodeversion.cpp -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 241.9 -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0 -fdeprecated-macro -fdebug-compilation-dir /Users/vagrant/miniconda/conda-bld/recipe_1486359815152/work/qt-everywhere-opensource-src-4.8.7 -ferror-limit 19 -fmessage-length 157 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.7.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fdiagnostics-show-option -vectorize-slp -o /var/tmp/xcodeversion-ab00a3.o -x c++ /Users/vagrant/miniconda/conda-bld/recipe_1486359815152/work/qt-everywhere-opensource-src-4.8.7/config.tests/mac/xcodeversion.cpp 
1.	/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:102:69: current parser token ','
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/tmp/xcodeversion-979c88.cpp
clang: note: diagnostic msg: /var/tmp/xcodeversion-979c88.sh
clang: note: diagnostic msg: 

********************
/Users/vagrant/miniconda/conda-bld/recipe_1486359815152/work/qt-everywhere-opensource-src-4.8.7/config.tests/mac/dwarf2.test: line 42: ./xcodeversion: No such file or directory
rm: xcodeversion: No such file or directory

This is the Qt for Mac OS X Open Source Edition.

You are licensed to use this software under the terms of
the Lesser GNU General Public License (LGPL) versions 2.1.
You are also licensed to use this software under the terms of
the GNU General Public License (GPL) versions 3.

Type '3' to view the GNU General Public License version 3.
Type 'L' to view the Lesser GNU General Public License version 2.1.
Type 'yes' to accept this license offer.
Type 'no' to decline this license offer.

Do you accept the terms of either license? 
Creating qmake. Please wait...
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/tmp/project-e7cbde.cpp
clang: note: diagnostic msg: /var/tmp/project-e7cbde.sh
clang: note: diagnostic msg: 

********************
make: *** [project.o] Error 254
Traceback (most recent call last):
  File "/Users/vagrant/miniconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/Users/vagrant/miniconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "/Users/vagrant/miniconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "/Users/vagrant/miniconda/lib/python3.5/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/Users/vagrant/miniconda/lib/python3.5/site-packages/conda_build/build.py", line 1478, in build_tree
    config=config)
  File "/Users/vagrant/miniconda/lib/python3.5/site-packages/conda_build/build.py", line 1057, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/Users/vagrant/miniconda/lib/python3.5/site-packages/conda_build/utils.py", line 592, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/Users/vagrant/miniconda/lib/python3.5/site-packages/conda_build/utils.py", line 588, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/Users/vagrant/miniconda/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/Users/vagrant/miniconda/conda-bld/recipe_1486359815152/work/qt-everywhere-opensource-src-4.8.7/conda_build.sh']' returned non-zero exit status 2
```

</details>

**Comment by gillins** [comment] 2017-02-06 06:40
Thanks for looking into this @jakirkham. Why the 10.7 runtime - I thought we were building for 10.9?

I suppose these kind of problems are why `clang` is 'unsupported' by Qt4... 

All I can tell you is that it works fine with `clang` 703.0.29 on 10.11. Hopefully we can find a slightly more recent `clang` that builds Qt4 but doesn't break our 10.9 compatibility. Is it possible to upgrade your OS/Xcode to a more recent version? Sorry I don't understand much about the details of OSX....

**Comment by mingwandroid** [comment] 2017-02-06 10:48
`export MACOSX_DEPLOYMENT_TARGET=10.9` to avoid this segfault.

**Comment by jakirkham** [comment] 2017-02-06 15:13
> `export MACOSX_DEPLOYMENT_TARGET=10.9` to avoid this segfault.

That's already done by the `toolchain`.

> Why the 10.7 runtime - I thought we were building for 10.9?

I think it is hard coded in Qt somewhere.

> Is it possible to upgrade your OS/Xcode to a more recent version?

Initially I was using 10.9 with XCode 6.1. Though largely we have switched to 10.10 with XCode 6.4 (still able to target 10.9 there). I can try to give that a go later. I have the VM already, but need to verify it has the right XCode.

**Comment by gillins** [comment] 2017-03-07 07:57
> That's already done by the `toolchain`.

The Qt 4 recipe does not use `toolchain` as far as I can see. Could this be the problem?

**Comment by pkgw** [comment] 2017-03-07 18:17
By the way, I think a parallel-installable `qt4` package is feasible — *if* you just stuff it all inside its own prefix, say `$PREFIX/qt4`. Anything that depends on `qt4` needs to have its build scripts customized, but that seems like an acceptable trade-off to me. I have a prototype recipe but am not to keen to start worrying about local-built packages and so on at the moment.

**Comment by ccordoba12** [comment] 2017-03-07 19:08
@pkgw, that will break compatibility between conda-forge and defaults, so I think we're not interested in following that path.

Besides, I invested a lot of time trying to make that work on my own (~ 6 months) and always ended up with a state of things that broke either Qt5 or Qt4.

**Comment by gillins** [comment] 2017-03-16 03:36
@jakirkham Does `export MACOSX_DEPLOYMENT_TARGET=10.9` fix the build crash?

**Comment by jakirkham** [comment] 2017-03-16 05:25
Pretty sure that I had set everything in `conda-forge-build-setup` except, perhaps, the #CPUs restriction. Though it is has been a while so I may be misremembering. That said, was using a macOS 10.9 VM with XCode 6.1. Switching to a macOS 10.10 VM with XCode 6.4. This is more inline with the current Travis CI image in use as opposed to the previous one. Going to run over night and we can see how that goes.

**Comment by jakirkham** [comment] 2017-03-16 07:04
Seems the new XCode made the difference. Have uploaded the package I built under a `test` label. Though we can move it to `main`. Would be nice if someone(s) ( @gillins @ccordoba12 😉 ) could test and verify this package works ok. For more info, have uploaded the [log]( https://gist.github.com/jakirkham/283212d40514c00fbafa35a124575a91 ) too.

**Comment by ccordoba12** [comment] 2017-03-16 19:39
@gillins, do you have some free time? I'm sorry but I don't have time to do it.

**Comment by gillins** [comment] 2017-03-16 21:30
Works well for me 😄 I can confirm that it is linking to `libc++` which is what we want. I'll be able to do more tests once `pyqt` is rebuilt against this.

**Comment by jakirkham** [comment] 2017-03-16 21:51
Great! Thanks for testing @gillins. So we could release it to `main` now. Or we could configure a builds of `pyqt` and `pyside` first (using the package from `test`) and release them also to `test` and try those. What do you think?

Also is the Qt5 recipe workable on macOS. Have you tested it @gillins? Or does it maybe need some work?

**Comment by ccordoba12** [comment] 2017-03-16 22:08
I compiled Qt5 on macOS and I can confirm compilation there is quite simple.

**Comment by jakirkham** [comment] 2017-03-16 22:21
Cool, thanks for the info @ccordoba12. I'll give that a go tonight.

**Comment by gillins** [comment] 2017-03-16 22:42
I'd probably prefer to put `pyqt` in `test` first but I don't have a strong opinion, not sure what is involved.

I haven't tried Qt5. @ccordoba12 were you able to get linking against `libc++` ok?

**Comment by jakirkham** [comment] 2017-03-16 22:47
> I'd probably prefer to put `pyqt` in `test` first but I don't have a strong opinion, not sure what is involved.

It's not difficult. Assuming we can get `pyqt` to build.

**Comment by ccordoba12** [comment] 2017-03-16 23:17
>  @ccordoba12 were you able to get linking against libc++ ok?

Yes, that build links against libc++ by default.

**Comment by jakirkham** [comment] 2017-03-17 07:31
I think we need PR ( https://github.com/conda-forge/qt-feedstock/pull/33 ) to proceed.

**Comment by jakirkham** [comment] 2017-03-17 07:44
Might also need some [tweaking]( http://stackoverflow.com/a/35098040 ). Seems Qt5 doesn't like the Command Line Tools.

**Comment by gillins** [comment] 2017-03-27 22:42
Have you tried building Qt5 on OSX @jakirkham? I get a link error with `icu` that I can't work out... I'm guessing it was ok for @ccordoba12 

Also, it appears that `MACOSX_DEPLOYMENT_TARGET` is set to10.7 by the recipe (https://github.com/conda-forge/qt-feedstock/blob/master/recipe/build.sh#L89). Should this be removed?

**Comment by jakirkham** [comment] 2017-03-28 11:28
I did a little while back, but had some issues with the selectors as noted in the previous comment.

Also Qt complained about how my compiler was configured. 😒 Haven't had time to look into this of since.

I agree the deployment target should either be bumped to 10.9, dropped from `build.sh` and the `toolchain` added, or something else.

**Comment by jakirkham** [comment] 2017-03-28 11:42
Has anyone tried using the Qt 4 package I uploaded with PySide or PyQt?

**Comment by jakirkham** [comment] 2017-03-28 11:42
^ @jschueller

**Comment by jschueller** [comment] 2017-03-28 11:50
yes, see https://github.com/conda-forge/qt-feedstock/issues/34

**Comment by jakirkham** [comment] 2017-04-11 15:29
Do you have a proposed fix, @jschueller? I don't really have time to debug Qt issues. Though can try to find some time to build a new version if you or someone else provides a patch.

**Comment by jakirkham** [comment] 2017-04-11 15:33
Are there other issues with the Qt4 package for Mac? Missing features is certainly unfortunate. That said, I don't recall having a good experience getting phonon working when I use to build and use Qt4 more regularly. Also generally I don't think missing features constitute a bug with the package, but a desirable enhancement instead. If there are no known bugs with this, maybe it is time to release it broadly.

**Comment by gillins** [comment] 2017-04-11 22:20
I'm just trying the [phonon patch](https://bugreports.qt.io/browse/QTBUG-37209) @jschueller linked to. Will report back.

**Comment by gillins** [comment] 2017-04-11 23:22
That seemed to fix the `pyside` phonon tests. I'll just check `pyqt` and then submit a new PR.

**Comment by gillins** [comment] 2017-04-11 23:43
See https://github.com/conda-forge/qt-feedstock/pull/37

**Comment by jakirkham** [comment] 2017-04-12 03:39
Something else that occurs to me. The computer I'm building this on has support for a lot of intrinsics. In particular, it has support for AVX2, SSE3, and SSE4.2. I'm not sure whether Qt is smart enough to do run time checking with this sort of thing or if it just hard codes whatever is found on the system it was built on. If it is the latter, maybe we should constrain the intrinsics Qt uses to some reasonable subset. Thoughts?

**Comment by jakirkham** [comment] 2017-09-07 14:22
Closing as this has already been built several times. If there are issues with how it was built, those can be new issues.

**Closed by jakirkham** 2017-09-07 14:22 UTC
